INSERT INTO `%TABLE_PREFIX%1620_gridtemplates` (`id`, `prio`, `title`, `description`, `columns`, `template`, `preview`) VALUES
		
	(1,	1,	'1-Spalter',	'1 Spalte (100%)',	1,	'<div>\r\n	<div>REX_GRID[1]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"1\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"100\",\r\n			\"title\": \"100%\"\r\n		}\r\n	]\r\n}'),
	
	(2,	2,	'2-Spalter',	'2 Spalten (alle gleich groß)',	2,	'<div class=\"2-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"2\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"50\",\r\n			\"title\": \"50%\"\r\n		},\r\n		{\r\n			\"width\": \"50\",\r\n			\"title\": \"50%\"\r\n		}\r\n	]\r\n}'),
	
	(3,	3,	'3-Spalter',	'3 Spalten (alle gleich groß)',	3,	'<div class=\"3-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"3\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"33.33\",\r\n			\"title\": \"33%\"\r\n		},\r\n		{\r\n			\"width\": \"33.33\",\r\n			\"title\": \"33%\"\r\n		},\r\n		{\r\n			\"width\": \"33.33\",\r\n			\"title\": \"33%\"\r\n		}\r\n	]\r\n}'),
	
	(4,	4,	'4-Spalter',	'4 Spalten (alle gleich groß)',	4,	'<div class=\"4-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n	<div>REX_GRID[4]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"4\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		},\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		},\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		},\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		}\r\n	]\r\n}'),
	
	(5,	5,	'5-Spalter',	'5 Spalten (alle gleich groß)',	5,	'<div class=\"5-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n	<div>REX_GRID[4]</div>\r\n	<div>REX_GRID[5]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"5\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"20\",\r\n			\"title\": \"20%\"\r\n		},\r\n		{\r\n			\"width\": \"20\",\r\n			\"title\": \"20%\"\r\n		},\r\n		{\r\n			\"width\": \"20\",\r\n			\"title\": \"20%\"\r\n		},\r\n		{\r\n			\"width\": \"20\",\r\n			\"title\": \"20%\"\r\n		},\r\n		{\r\n			\"width\": \"20\",\r\n			\"title\": \"20%\"\r\n		}\r\n	]\r\n}'),
	
	(6,	6,	'6-Spalter',	'6 Spalten (alle gleich groß)',	6,	'<div class=\"6-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n	<div>REX_GRID[4]</div>\r\n	<div>REX_GRID[5]</div>\r\n	<div>REX_GRID[6]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"6\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		}\r\n	]\r\n}'),
	
	(7,	7,	'80% - 20%',	'2 Spalten (80% - 20%)',	2,	'<div class=\"2-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"2\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"80\",\r\n			\"title\": \"80%\"\r\n		},\r\n		{\r\n			\"width\": \"20\",\r\n			\"title\": \"20%\"\r\n		}\r\n	]\r\n}'),
	
	(8,	8,	'20% - 80%',	'2 Spalten (20% - 80%)',	2,	'<div class=\"2-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"2\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"20\",\r\n			\"title\": \"20%\"\r\n		},\r\n		{\r\n			\"width\": \"80\",\r\n			\"title\": \"80%\"\r\n		}\r\n	]\r\n}'),
	
	(9,	9,	'70% - 30%',	'2 Spalten (70% - 30%)',	2,	'<div class=\"2-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"2\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"70\",\r\n			\"title\": \"70%\"\r\n		},\r\n		{\r\n			\"width\": \"30\",\r\n			\"title\": \"30%\"\r\n		}\r\n	]\r\n}'),
	
	(10,	10,	'30% - 70%',	'2 Spalten (30% - 70%)',	2,	'<div class=\"2-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"2\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"30\",\r\n			\"title\": \"30%\"\r\n		},\r\n		{\r\n			\"width\": \"70\",\r\n			\"title\": \"70%\"\r\n		}\r\n	]\r\n}'),
	
	(11,	11,	'60% - 40%',	'2 Spalten (60% - 40%)',	2,	'<div class=\"2-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"2\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"60\",\r\n			\"title\": \"60%\"\r\n		},\r\n		{\r\n			\"width\": \"40\",\r\n			\"title\": \"40%\"\r\n		}\r\n	]\r\n}'),
	
	(12,	12,	'40% - 60%',	'2 Spalten (40% - 60%)',	2,	'<div class=\"2-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"2\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"40\",\r\n			\"title\": \"40%\"\r\n		},\r\n		{\r\n			\"width\": \"60\",\r\n			\"title\": \"60%\"\r\n		}\r\n	]\r\n}'),
	
	(13,	13,	'25% - 50% - 25%',	'3 Spalten (25% - 50% - 25%)',	3,	'<div class=\"3-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"3\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		},\r\n		{\r\n			\"width\": \"50\",\r\n			\"title\": \"50%\"\r\n		},\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		}\r\n	]\r\n}'),
	
	(14,	14,	'50% - 25% - 25%',	'3 Spalten (50% - 25% - 25%)',	3,	'<div class=\"3-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"3\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"50\",\r\n			\"title\": \"50%\"\r\n		},\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		},\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		}\r\n	]\r\n}'),
	
	(15,	15,	'25% - 25% - 50%',	'3 Spalten (25% - 25% - 50%)',	3,	'<div class=\"3-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"3\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		},\r\n		{\r\n			\"width\": \"25\",\r\n			\"title\": \"25%\"\r\n		},\r\n		{\r\n			\"width\": \"50\",\r\n			\"title\": \"50%\"\r\n		}\r\n	]\r\n}'),
	
	(16,	16,	'1/6 - 4/6 - 1/6',	'3 Spalten (1/6 - 4/6 - 1/6)',	3,	'<div class=\"3-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"3\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},\r\n		{\r\n			\"width\": \"66.67\",\r\n			\"title\": \"4/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		}\r\n	]\r\n}'),
	
	(17,	17,	'4/6 - 1/6 - 1/6',	'3 Spalten (4/6 - 1/6 - 1/6)',	3,	'<div class=\"3-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"3\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"66.67\",\r\n			\"title\": \"4/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},		\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		}\r\n	]\r\n}'),
	
	(18,	18,	'1/6 - 1/6 - 4/6',	'3 Spalten (1/6 - 1/6 - 4/6)',	3,	'<div class=\"3-spalter\">\r\n	<div>REX_GRID[1]</div>\r\n	<div>REX_GRID[2]</div>\r\n	<div>REX_GRID[3]</div>\r\n</div>',	'{\r\n	\"totalcolumns\": \"3\",\r\n	\"columns\": [\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},\r\n		{\r\n			\"width\": \"16.66\",\r\n			\"title\": \"1/6\"\r\n		},		\r\n		{\r\n			\"width\": \"66.67\",\r\n			\"title\": \"4/6\"\r\n		}\r\n	]\r\n}');